# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Rand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Rand.proto',
  package='pkg_Rand',
  syntax='proto3',
  serialized_pb=_b('\n\nRand.proto\x12\x08pkg_Rand\"s\n\x0bRandRequest\x12\x10\n\x08SendText\x18\x01 \x01(\x08\x12\x12\n\nSendNumber\x18\x02 \x01(\x08\x12\x12\n\nTextLength\x18\x03 \x01(\x03\x12\x13\n\x0bNumberFloor\x18\x04 \x01(\x03\x12\x15\n\rNumberCeiling\x18\x05 \x01(\x03\",\n\x0cRandResponse\x12\x0c\n\x04Text\x18\x01 \x01(\t\x12\x0e\n\x06Number\x18\x02 \x01(\x03\x32I\n\tRandValue\x12<\n\tRandValue\x12\x15.pkg_Rand.RandRequest\x1a\x16.pkg_Rand.RandResponse\"\x00\x62\x06proto3')
)




_RANDREQUEST = _descriptor.Descriptor(
  name='RandRequest',
  full_name='pkg_Rand.RandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SendText', full_name='pkg_Rand.RandRequest.SendText', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SendNumber', full_name='pkg_Rand.RandRequest.SendNumber', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TextLength', full_name='pkg_Rand.RandRequest.TextLength', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NumberFloor', full_name='pkg_Rand.RandRequest.NumberFloor', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NumberCeiling', full_name='pkg_Rand.RandRequest.NumberCeiling', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=139,
)


_RANDRESPONSE = _descriptor.Descriptor(
  name='RandResponse',
  full_name='pkg_Rand.RandResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Text', full_name='pkg_Rand.RandResponse.Text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Number', full_name='pkg_Rand.RandResponse.Number', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=185,
)

DESCRIPTOR.message_types_by_name['RandRequest'] = _RANDREQUEST
DESCRIPTOR.message_types_by_name['RandResponse'] = _RANDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RandRequest = _reflection.GeneratedProtocolMessageType('RandRequest', (_message.Message,), dict(
  DESCRIPTOR = _RANDREQUEST,
  __module__ = 'Rand_pb2'
  # @@protoc_insertion_point(class_scope:pkg_Rand.RandRequest)
  ))
_sym_db.RegisterMessage(RandRequest)

RandResponse = _reflection.GeneratedProtocolMessageType('RandResponse', (_message.Message,), dict(
  DESCRIPTOR = _RANDRESPONSE,
  __module__ = 'Rand_pb2'
  # @@protoc_insertion_point(class_scope:pkg_Rand.RandResponse)
  ))
_sym_db.RegisterMessage(RandResponse)



_RANDVALUE = _descriptor.ServiceDescriptor(
  name='RandValue',
  full_name='pkg_Rand.RandValue',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=187,
  serialized_end=260,
  methods=[
  _descriptor.MethodDescriptor(
    name='RandValue',
    full_name='pkg_Rand.RandValue.RandValue',
    index=0,
    containing_service=None,
    input_type=_RANDREQUEST,
    output_type=_RANDRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RANDVALUE)

DESCRIPTOR.services_by_name['RandValue'] = _RANDVALUE

# @@protoc_insertion_point(module_scope)
